# Generated by Django 5.0.6 on 2024-07-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_adress_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='delivery_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
