# Generated by Django 5.0.6 on 2024-07-14 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_returnorders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnorders',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.orders'),
        ),
    ]
