# Generated by Django 5.0.6 on 2024-07-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_returnorders_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='return_status',
            field=models.CharField(default='not returned', max_length=30),
        ),
    ]
